### ISSUE TITLE
Need to copy schedule from legacy site into azuracast

### ISSUE THREAD

**Issue by keybrdist** [dnbradio/dnbradio-issue-tracker#1]
Setup schedule for all dj's
https://cast.dnbradio.com/station/1/streamers 
click edit next to dj name
under the schedule tab, set the show start and end time (in UTC aka GMT)
you only need to set the time and day of week
if the show is not weekly, go ahead and setup the show to be weekly but also add a comment in the basic info section noting whether the show is bi-weekly or monthly or whatever. We will use these notes later.

Note: to see all shows in GMT, go to dnbradio.com/schedule and change the timezone to GMT.

![image](https://github.com/dnbradio/dnbradio-issue-tracker/assets/3534206/d12a02e8-ffc4-4897-aff1-1c19d4bc21a2)
![image](https://github.com/dnbradio/dnbradio-issue-tracker/assets/3534206/64764694-da25-40ef-9e7a-7c505b32bc6d)

**Comment by RobDizygotic** [comment]
DJ Scheduling Update (I may double check again if I missed a schedule entry for any of the below but I think I'm correct. Looks pretty full on the schedule view page. Below are notes with some additional comments not all added to the notes of the DJ account entry. 

Agonetik (Detroit - USA) Neuro Drum and Bass Fury - 05:30 AM to 07:30 AM GMT on Sundays - Appears to be a weekly show. As previously mentioned in our discord chat, this DJ doesn't appear to have an account entry to enter in his scheduled slot. Is this still a current DJ?

Southpaw - Not missing and the usual schedule entry has been added but a note added to work updates for reference. The below has been added to DJ's schedule entry comments. 
Every 2nd, 3rd, and 4th Saturday of the month. (RobDizygotic Note - Has mentioned is due a baby and mentioned a replacement I can't think currently of or will be probably doing a paternity style leave for a while for his show.) Chase up Southpaw to confirm future scheduling or DJ cover.

Balistik
Fortnightly Show (Bi-Monthly) Should be alternate weeks with Parallel Motion.

Disorder Crew
Sounds very similar to Disorderly Conduct Radio with Ruksa and Solve and already has another DJ entry with their scheduled show set. If not then it's a Renegade - No scheduled show set.

dmdown	dmdown
Renegade - No scheduled show set.

emplate	emplate
Renegade - No scheduled show set. (Didn't he get angry at another DJ and left a while back IIRC? I wouldn't like to confirm)

John Glist	johnglist
Renegade - No scheduled show set.

ParallelMotion	parallelmotion
Should be alternate weeks with Balistik as a weekly show would clash every other week.

Plasmator	plasmator
Renegade - No scheduled show set.

Respect DnB (LA)	respectdnb
Renegade - No scheduled show set.

Shark	shark
Renegade - No scheduled show set. Shark flocked to a different ocean.

shoebox	shoebox
Renegade (boss) Master - No scheduled show set.

Valis	valis
Renegade - No scheduled show set.

**Comment by keybrdist** [comment]
Re: Agonetik -- Remove him from the dnbradio.com/schedule please. They have not been around since April.

Looks like you found everyone else. We can close this issue.

**Comment by RobDizygotic** [comment]
Initially complete and notes sent on discord.

**Comment by RobDizygotic** [comment]
Cool, thank you.
