### ISSUE TITLE
Proof-reading - Find typos in existing pages

### ISSUE THREAD

**Issue by keybrdist** [dnbradio/dnbradio-issue-tracker#10]
Help us find any typos. Post screenshots and include page link where the typo occurs.

https://staging.dnbradio.com

**Comment by leonidlewis** [comment]
![image](https://github.com/dnbradio/issues/assets/83287135/600230ab-93f2-4163-840b-d6b7a02a5c40)
https://staging.dnbradio.com/podcast
![image](https://github.com/dnbradio/issues/assets/83287135/75877a64-4500-42ba-a58d-21741d49f007)

https://staging.dnbradio.com/schedule
![image](https://github.com/dnbradio/issues/assets/83287135/38641bd8-3245-43bd-9a01-ba61dc807899)

https://staging.dnbradio.com/contact
![image](https://github.com/dnbradio/issues/assets/83287135/6cb5a989-13cd-4ab5-a740-26760d5ce070)
https://staging.dnbradio.com/
![image](https://github.com/dnbradio/issues/assets/83287135/97a2f5b9-eba8-4c86-ab4b-1c71a4e18a21)
https://staging.dnbradio.com/terms
"which can be found at the link to the Privacy Policy."
