### ISSUE TITLE
FAQ page needed

### ISSUE THREAD

**Issue by keybrdist** [dnbradio/dnbradio-issue-tracker#13]
Should answer all the basic questions:

- How do I tune in?
- How do I chat?
- What is the purpose of this site?
- How do I become a dj on dnbradio?
- How do I get my music onto dnbradio?
- How can I donate?
- What do you do with the donations?
- Do you have merch?
- How can I volunteer as a developer?
- How can I get further help?

Links to Discord and Twitter at the bottom for further contact.

**Comment by leonidlewis** [comment]
please review these answers

How do I tune in?
You can tune in by visiting our website and navigating to the "Listen Live" or "Live Stream" section. There, you'll find the player to stream our broadcasts.

How do I chat?
To join the chat, you can find the chatroom on our website where listeners and DJs interact. Look for the chatbox or a designated chat section while listening to the live stream.

What is the purpose of this site?
Our site is a platform dedicated to broadcasting drum and bass music, fostering a community around this genre, and providing a space for DJs and listeners to connect and enjoy music together.

How do I become a DJ on dnbradio?
To become a DJ on dnbradio, you can reach out to us through our website's contact or submission form. Provide information about your DJ experience, style, and why you'd like to join our lineup.

How do I get my music onto dnbradio?
We often accept music submissions from artists. Use the submission form on our website to send us your tracks or mixes. Our team will review the submissions, and if it aligns with our content, we might feature it on our broadcasts.

How can I donate?
Donations can be made through our website via a designated donation link or button. Look for "Support Us" or "Donate" sections on the site.

What do you do with the donations?
Donations primarily support the operational costs of running the radio station, including server maintenance, licensing, and improving the overall experience for our community.

Do you have merch?
Yes, we often have merchandise available. Check out our website's "Store" or "Merchandise" section to see if there are any items currently for sale.

How can I volunteer as a developer?
If you're interested in volunteering as a developer, please contact us through our website. Share your skills, experiences, and how you would like to contribute to the platform's development.

How can I get further help?
For additional assistance or inquiries not covered here, you can visit our website's "Contact" or "Support" section to reach out to our support team. Alternatively, you might find information in our FAQ section that addresses specific concerns or questions.

**Comment by keybrdist** [comment]
Thanks @leonidlewis -- these are fine. I will make my adjustments after the page is merged to staging.
