### ISSUE TITLE
Trigger Twitch video stream when dj connects

### ISSUE THREAD

**Issue by keybrdist** [dnbradio/dnbradio-issue-tracker#18]
We want to trigger our Twitch cast to start streaming as soon as a dj connects..

**Comment by keybrdist** [comment]
Andy, when you start on this lmk and we can work together to come up with a solution. I need to show you how our OBS instance works, etc.

**Comment by keybrdist** [comment]
@leonidlewis  please check into this and test it out locally. https://chatgpt.com/share/787ab9ad-112c-422a-9fdf-5e38621c51b6

**Comment by keybrdist** [comment]
Please post your findings re: connecting over remote network to control OBS (this is because the OBS instance will be hosted on a different server than the Laravel server)

**Comment by keybrdist** [comment]
@leonidlewis please see my comment

**Comment by leonidlewis** [comment]
@keybrdist I believe you've already fixed this issue. If then, please close the issue.
