### ISSUE TITLE
Third-party radio directories - need to add/update dnbradio listing

### ISSUE THREAD

**Issue by keybrdist** [dnbradio/dnbradio-issue-tracker#2]
Check links listed here to make sure dnbradio is properly listed and that playback works. 

https://www.azuracast.com/docs/user-guide/promoting-your-station/

We may need to update some of these or create an account (with the team dnbradio email address) so that we can be listed in their directories.

Please do not change anything our streaming admin until we discussed and reviewed the necessary changes with the dev team.

**Comment by keybrdist** [comment]
@RobDizygotic 

Here is the live streaming information we should provide these sites (if applicable).

Station Name: DnBRadio.com - 24/7 Drum & Bass
Website: https://dnbradio.com
Description: 24/7 Drum and Bass with LIVE dj's from around the globe! 

Genre1: Drum and Bass
Genre2 (if applicable): Electronic

^^ if there is a singel field called Genres (plural), then enter: Drum and Bass, Electronic

Streaming URLs (if applicable):
Streaming URL1: https://source.dnbradio.com/dnbradio_main.mp3
Streaming URL2: https://dnbradio.nl/dnbradio_main.mp3

Radio Status Page (if applicable):
http://source.dnbradio.com:8000/index.html?sid=1 
^ notice: http only (no https)

**Comment by keybrdist** [comment]
Re: Internet-Radio.
Here is the form to fill out. Note: They also want us to link to them.
https://www.internet-radio.com/add/ - I'm working on this now. Probably will be done in another day, so please wait before submitting..

**Comment by keybrdist** [comment]
Re: Radio-Browser. I will make changes to our setup to follow these instructions.
https://www.radio-browser.info/owners

**Comment by RobDizygotic** [comment]
Extra directory below to look also look at.
https://radio.co/blog/internet-radio-directories-submit-promote

**Comment by RobDizygotic** [comment]
Internet-Radio - Done
Radio.de/net - Done
GetmeRadio - Done
Radio Browser - Done
Xiph.org Directory & IceCast YP - Done
TuneinAir - Done
