### ISSUE TITLE
Need testing of login and registration flow

### ISSUE THREAD

**Issue by keybrdist** [dnbradio/dnbradio-issue-tracker#21]
- [x] New Registration
  - [x] #23
  - [x] Test the resend verification button to make sure it works
- [x] Login - make sure login/logout works as expected
- [x] Email re-verification
  - [x] Try changing your email. This should trigger a new verification email to be sent to you
  - [x] This should also cause your account to go into a "unverified" status until you click the link. I'm not sure if you will even see this on the website, but I can check the database directly if you let me know (before you click the link).
- [x] Lost Password - make sure you are able to set a new password
- [x] Edit Profile - test editing all fields in the profile including images.
  - [x] Make sure all URL fields show an error and do not let you submit the form if the URL is not valid.
  - [x] Make sure that all date fields are of type date and show a date picker.
  - [x] Make note of any fields that do not appear to have proper validation or that should not be editable by the user.
- [x] Edit Schedule - test all fields
  - [x] Make sure all URL fields show an error and do not let you submit the form if the URL is not valid.
  - [x] Make sure that all date fields are of type date and show a date picker.
  - [x] Make note of any fields that do not appear to have proper validation or that should not be editable by the user.
- [x] Edit Podcast Item - test all fields, test tracklist parsing
  - [x] Make sure all URL fields show an error and do not let you submit the form if the URL is not valid.
  - [x] Make sure that all date fields are of type date and show a date picker.
  - [x] Make note of any fields that do not appear to have proper validation or that should not be editable by the user.

**Comment by keybrdist** [comment]
@RobDizygotic note: All "Edit Pages" are still in development. I expect there to be some bugs, but feel free to try them out.

**Comment by keybrdist** [comment]
@RobDizygotic the staging site has been updated. Please let me know if your version doesn't look like this (all black background).

<img width="1901" alt="image" src="https://github.com/dnbradio/issues/assets/3534206/6c80bade-76f8-4750-8263-706d7a91d5ad">

**Comment by leonidlewis** [comment]
@keybrdist I've fixed the email verification issue

**Comment by keybrdist** [comment]
@leonidlewis -- please make sure the user has the ability to resend the verification email somewhere on the UI. I am not sure the appropriate place so please make a suggestion.

**Comment by leonidlewis** [comment]
![image](https://github.com/dnbradio/issues/assets/83287135/3fd77ce8-30ef-43f8-aa8c-31ea8b1da3f2)
This is what I've seen while testing.

**Comment by leonidlewis** [comment]
Testing done and fixed some issues that cause the website block

**Comment by leonidlewis** [comment]
![image](https://github.com/dnbradio/issues/assets/83287135/6af4e3c3-0095-45ec-948b-3c641ad7dd80)
Here, the user should be available to go back to the home or register page, if he sees the above message.
