### ISSUE TITLE
Add all wide format show banners to the schedule

### ISSUE THREAD

**Issue by keybrdist** [dnbradio/dnbradio-issue-tracker#3]
Add to the following place:
https://dnbradio.com/schedule

Note: We will import these into the new site automatically when the time comes.

**Comment by keybrdist** [comment]
@RobDizygotic just fyi - I've already done the initial uploading, but as we get new banners from mazco, we need to:

1.) Upload the square version to the dj profile on Azura
2.) Upload the wide version onto the dnbradio.com/schedule page

**Comment by RobDizygotic** [comment]
Will continue with the other tasks and come back to this as and when we get banners in.
